properties:
  form:
    properties:
      alert:
        properties:
          additionalRuleLabels:
            additionalProperties:
              type: string
            type: object
          annotations:
            additionalProperties:
              type: string
            type: object
          enabled:
            enum:
            - none
            - critical
            - warning
            - info
            type: string
          groups:
            properties:
              connectivity:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsHighActiveConnections:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamDisabled:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      natsSlowConsumers:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      natsStaleConnections:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      natsStalledClients:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      natsSuddenConnectionDrop:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - natsHighActiveConnections
                    - natsJetStreamDisabled
                    - natsSlowConsumers
                    - natsStaleConnections
                    - natsStalledClients
                    - natsSuddenConnectionDrop
                    type: object
                required:
                - enabled
                - rules
                type: object
              consumerHealth:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsJetStreamBacklogNoProgress:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamHighAckPending:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamHighPendingMessages:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamHighPendingMessagesWarning:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - natsJetStreamBacklogNoProgress
                    - natsJetStreamHighAckPending
                    - natsJetStreamHighPendingMessages
                    - natsJetStreamHighPendingMessagesWarning
                    type: object
                required:
                - enabled
                - rules
                type: object
              consumerManagement:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsHighTotalConsumers:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsSuddenConsumerDrop:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - natsHighTotalConsumers
                    - natsSuddenConsumerDrop
                    type: object
                required:
                - enabled
                - rules
                type: object
              core:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsDown:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      natsReplicasNotReady:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - natsDown
                    - natsReplicasNotReady
                    type: object
                required:
                - enabled
                - rules
                type: object
              resourceUtilization:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsJetStreamHighMemoryUsage:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamHighStorageUsage:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - natsJetStreamHighMemoryUsage
                    - natsJetStreamHighStorageUsage
                    type: object
                required:
                - enabled
                - rules
                type: object
              streamPerformance:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      natsJetStreamNearByteLimit:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      natsJetStreamNearMessageLimit:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - natsJetStreamNearByteLimit
                    - natsJetStreamNearMessageLimit
                    type: object
                required:
                - enabled
                - rules
                type: object
            required:
            - connectivity
            - consumerHealth
            - consumerManagement
            - core
            - resourceUtilization
            - streamPerformance
            type: object
          labels:
            additionalProperties:
              type: string
            type: object
        required:
        - enabled
        - groups
        - labels
        type: object
    required:
    - alert
    type: object
  grafana:
    properties:
      apikey:
        type: string
      enabled:
        type: boolean
      jobName:
        type: string
      url:
        type: string
      version:
        type: string
    required:
    - apikey
    - enabled
    - jobName
    - url
    - version
    type: object
  metadata:
    properties:
      release:
        properties:
          name:
            type: string
          namespace:
            type: string
        required:
        - name
        - namespace
        type: object
      resource:
        description: ResourceID identifies a resource
        properties:
          group:
            type: string
          kind:
            description: Kind is the serialized kind of the resource.  It is normally
              CamelCase and singular.
            type: string
          name:
            description: 'Name is the plural name of the resource to serve.  It must
              match the name of the CustomResourceDefinition-registration

              too: plural.group and it must be all lowercase.'
            type: string
          scope:
            description: ResourceScope is an enum defining the different scopes available
              to a custom resource
            type: string
          version:
            type: string
        required:
        - group
        type: object
    required:
    - release
    - resource
    type: object
required:
- form
- grafana
type: object
