---
# Source: qdrant-alerts/templates/alert.yaml


  
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: release-name
  namespace: default
  labels:
    helm.sh/chart: qdrant-alerts-v2025.6.30
    app.kubernetes.io/name: qdrant-alerts
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.5.0"
    app.kubernetes.io/managed-by: Helm
    release: prometheus
spec:
  groups:
  - name: qdrant.database.default.release-name.rules
      rules:
    - alert: QdrantDown
          expr: kubedb_com_qdrant_status_phase{app="release-name", namespace="default",phase="NotReady"} >= 1
          for: 30s
          labels:
            severity: critical
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Qdrant database is in NotReady state (instance {{ $labels.instance }})
            description: "Database in NotReady state, database read/write is failing.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: QdrantPhaseCritical
          expr: kubedb_com_qdrant_status_phase{app="release-name", namespace="default",phase="Critical"} >= 1
          for: 1m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Qdrant database is in Critical state (instance {{ $labels.instance }})
            description: "Database in Critical state, one or more database nodes are not working properly.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: QdrantRestarted
          expr: (qdrant_uptime{job=~"release-name-stats",namespace="default"}) < 180
          for: 1m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Qdrant service restart (instance {{ $labels.pod }})
            description: "Qdrant service restart on {{ $labels.pod }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: QdrantHighCPUUsage
          expr: |
            (
              sum(
                sum by (namespace, pod, container)(
                  irate(container_cpu_usage_seconds_total{
                    image!="",
                    job="kubelet",
                    metrics_path="/metrics/cadvisor",
                    namespace="default",
                    pod=~"^release-name.*"
                  }[5m])
                ) * on (namespace, pod) group_left(node)
                topk by (namespace, pod)(1,
                  max by (namespace, pod, node)(
                    kube_pod_info{
                      node!="",
                      namespace="default",
                      pod=~"^release-name.*"
                    }
                  )
                )
              ) by (pod)
            )
            /
            sum(
              cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{
                namespace="default",
                pod=~"^release-name.*"
              }
            ) by (pod)
            > 0.8
          for: 1m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Qdrant Pod CPU usage high (pod {{ $labels.pod }})
            description: "Qdrant pod CPU usage is above 0.8 (ratio of usage to limits).\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: QdrantHighMemoryUsage
          expr: |
            (
              sum(
                container_memory_working_set_bytes{
                  namespace="default",
                  pod=~"^release-name.*",
                  container!="",
                  image!=""
                }
              ) by (pod)
            )
            /
            sum(
              cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{
                namespace="default",
                pod=~"^release-name.*"
              }
            ) by (pod)
            > 0.8
          for: 1m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Qdrant Pod Memory usage high (pod {{ $labels.pod }})
            description: "Qdrant pod memory usage is above 0.8 (ratio of working_set to limits).\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: QdrantHighPendingOperations
      expr: |
        sum by (pod) (
          cluster_pending_operations_total{
            job=~"release-name-stats",
            namespace="default",
            pod=~"^release-name.*"
          }
        ) > 10
      for: 5m
      labels:
        severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
      annotations:
        summary: Qdrant pending operations high on pod {{ $labels.pod }}
        description: |
          Qdrant pod has too many pending operations.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

    - alert: QdrantGrpcResponsesFailHigh
      expr: |
        sum by (pod) (
          increase(
            grpc_responses_fail_total{
              job=~"release-name-stats",
              namespace="default",
              pod=~"^release-name.*"
            }[5m]
          )
        ) > 5
      for: 5m
      labels:
        severity: critical
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
      annotations:
        summary: Qdrant gRPC fails high on pod {{ $labels.pod }}
        description: |
          The number of failed gRPC responses for this pod in the last 5m exceeds threshold.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

    - alert: DiskUsageHigh
          expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"release-name-.+$",namespace=~"default"}) ) )
            * 100 > 80
          for: 1m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Persistent Volume Usages in instance {{ $labels.instance }}
            description: "Persistent Volume Usages\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: DiskAlmostFull
          expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"release-name-.+$",namespace=~"default"}) ) )
            * 100 > 95
          for: 1m
          labels:
            severity: critical
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: Persistent Volume Usages in instance {{ $labels.instance }}
            description: "Persistent Volume Usages\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - name: qdrant.provisioner.default.release-name.rules
      rules:
    - alert: KubeDBQdrantPhaseNotReady
          expr: kubedb_com_qdrant_status_phase{phase="NotReady",app="release-name",namespace="default"} == 1
          for: 1m
          labels:
            severity: critical
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: KubeDB Qdrant Phase NotReady (qdrant {{ $labels.qdrant }})
            description: "KubeDB Qdrant Phase not ready on {{ $labels.qdrant }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubeDBQdrantPhaseCritical
          expr: kubedb_com_qdrant_status_phase{phase="Critical",app="release-name",namespace="default"} == 1
          for: 15m
          labels:
            severity: warning
        k8s_group: kubedb.com
        k8s_kind: Qdrant
        k8s_resource: qdrants
        app: release-name
        app_namespace: default
          annotations:
            summary: KubeDB Qdrant Phase Critical (qdrant {{ $labels.qdrant }})
            description: "KubeDB Qdrant Phase Critical {{ $labels.qdrant }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
