//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertRuleSelector) DeepCopyInto(out *AlertRuleSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertRuleSelector.
func (in *AlertRuleSelector) DeepCopy() *AlertRuleSelector {
	if in == nil {
		return nil
	}
	out := new(AlertRuleSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAlert) DeepCopyInto(out *FixedAlert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAlert.
func (in *FixedAlert) DeepCopy() *FixedAlert {
	if in == nil {
		return nil
	}
	out := new(FixedAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatValAlertConfig) DeepCopyInto(out *FloatValAlertConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatValAlertConfig.
func (in *FloatValAlertConfig) DeepCopy() *FloatValAlertConfig {
	if in == nil {
		return nil
	}
	out := new(FloatValAlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntValAlert) DeepCopyInto(out *IntValAlert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntValAlert.
func (in *IntValAlert) DeepCopy() *IntValAlert {
	if in == nil {
		return nil
	}
	out := new(IntValAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBAlert) DeepCopyInto(out *MariaDBAlert) {
	*out = *in
	out.RuleSelector = in.RuleSelector
	out.Groups = in.Groups
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBAlert.
func (in *MariaDBAlert) DeepCopy() *MariaDBAlert {
	if in == nil {
		return nil
	}
	out := new(MariaDBAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBAlertGroups) DeepCopyInto(out *MariaDBAlertGroups) {
	*out = *in
	out.Database = in.Database
	out.Cluster = in.Cluster
	out.Kubedb = in.Kubedb
	out.Opsrequest = in.Opsrequest
	out.Stash = in.Stash
	out.Schema = in.Schema
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBAlertGroups.
func (in *MariaDBAlertGroups) DeepCopy() *MariaDBAlertGroups {
	if in == nil {
		return nil
	}
	out := new(MariaDBAlertGroups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBCluster) DeepCopyInto(out *MariaDBCluster) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBCluster.
func (in *MariaDBCluster) DeepCopy() *MariaDBCluster {
	if in == nil {
		return nil
	}
	out := new(MariaDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBClusterRules) DeepCopyInto(out *MariaDBClusterRules) {
	*out = *in
	out.GaleraReplicationLatencyTooLong = in.GaleraReplicationLatencyTooLong
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBClusterRules.
func (in *MariaDBClusterRules) DeepCopy() *MariaDBClusterRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBClusterRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBDatabase) DeepCopyInto(out *MariaDBDatabase) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBDatabase.
func (in *MariaDBDatabase) DeepCopy() *MariaDBDatabase {
	if in == nil {
		return nil
	}
	out := new(MariaDBDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBDatabaseRules) DeepCopyInto(out *MariaDBDatabaseRules) {
	*out = *in
	out.MySQLInstanceDown = in.MySQLInstanceDown
	out.MySQLServiceDown = in.MySQLServiceDown
	out.MySQLTooManyConnections = in.MySQLTooManyConnections
	out.MySQLHighThreadsRunning = in.MySQLHighThreadsRunning
	out.MySQLSlowQueries = in.MySQLSlowQueries
	out.MySQLInnoDBLogWaits = in.MySQLInnoDBLogWaits
	out.MySQLRestarted = in.MySQLRestarted
	out.MySQLHighQPS = in.MySQLHighQPS
	out.MySQLHighIncomingBytes = in.MySQLHighIncomingBytes
	out.MySQLHighOutgoingBytes = in.MySQLHighOutgoingBytes
	out.MySQLTooManyOpenFiles = in.MySQLTooManyOpenFiles
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBDatabaseRules.
func (in *MariaDBDatabaseRules) DeepCopy() *MariaDBDatabaseRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBDatabaseRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBKubedb) DeepCopyInto(out *MariaDBKubedb) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBKubedb.
func (in *MariaDBKubedb) DeepCopy() *MariaDBKubedb {
	if in == nil {
		return nil
	}
	out := new(MariaDBKubedb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBKubedbRules) DeepCopyInto(out *MariaDBKubedbRules) {
	*out = *in
	out.KubeDBMariaDBPhaseNotReady = in.KubeDBMariaDBPhaseNotReady
	out.KubeDBMariaDBPhaseCritical = in.KubeDBMariaDBPhaseCritical
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBKubedbRules.
func (in *MariaDBKubedbRules) DeepCopy() *MariaDBKubedbRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBKubedbRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBOpsrequest) DeepCopyInto(out *MariaDBOpsrequest) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBOpsrequest.
func (in *MariaDBOpsrequest) DeepCopy() *MariaDBOpsrequest {
	if in == nil {
		return nil
	}
	out := new(MariaDBOpsrequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBOpsrequestRules) DeepCopyInto(out *MariaDBOpsrequestRules) {
	*out = *in
	out.KubeDBMariaDBOpsRequestOnProgress = in.KubeDBMariaDBOpsRequestOnProgress
	out.KubeDBMariaDBOpsRequestStatusProgressingToLong = in.KubeDBMariaDBOpsRequestStatusProgressingToLong
	out.KubeDBMariaDBOpsRequestFailed = in.KubeDBMariaDBOpsRequestFailed
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBOpsrequestRules.
func (in *MariaDBOpsrequestRules) DeepCopy() *MariaDBOpsrequestRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBOpsrequestRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBSchema) DeepCopyInto(out *MariaDBSchema) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBSchema.
func (in *MariaDBSchema) DeepCopy() *MariaDBSchema {
	if in == nil {
		return nil
	}
	out := new(MariaDBSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBSchemaRules) DeepCopyInto(out *MariaDBSchemaRules) {
	*out = *in
	out.KubeDBMariaDBSchemaPendingForTooLong = in.KubeDBMariaDBSchemaPendingForTooLong
	out.KubeDBMariaDBSchemaInProgressForTooLong = in.KubeDBMariaDBSchemaInProgressForTooLong
	out.KubeDBMariaDBSchemaTerminatingForTooLong = in.KubeDBMariaDBSchemaTerminatingForTooLong
	out.KubeDBMariaDBSchemaFailed = in.KubeDBMariaDBSchemaFailed
	out.KubeDBMariaDBSchemaExpired = in.KubeDBMariaDBSchemaExpired
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBSchemaRules.
func (in *MariaDBSchemaRules) DeepCopy() *MariaDBSchemaRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBSchemaRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBStash) DeepCopyInto(out *MariaDBStash) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBStash.
func (in *MariaDBStash) DeepCopy() *MariaDBStash {
	if in == nil {
		return nil
	}
	out := new(MariaDBStash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBStashRules) DeepCopyInto(out *MariaDBStashRules) {
	*out = *in
	out.MariaDBStashBackupSessionFailed = in.MariaDBStashBackupSessionFailed
	out.MariaDBStashRestoreSessionFailed = in.MariaDBStashRestoreSessionFailed
	out.MariaDBStashNoBackupSessionForTooLong = in.MariaDBStashNoBackupSessionForTooLong
	out.MariaDBStashRepositoryCorrupted = in.MariaDBStashRepositoryCorrupted
	out.MariaDBStashRepositoryStorageRunningLow = in.MariaDBStashRepositoryStorageRunningLow
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBStashRules.
func (in *MariaDBStashRules) DeepCopy() *MariaDBStashRules {
	if in == nil {
		return nil
	}
	out := new(MariaDBStashRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mariadb) DeepCopyInto(out *Mariadb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mariadb.
func (in *Mariadb) DeepCopy() *Mariadb {
	if in == nil {
		return nil
	}
	out := new(Mariadb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mariadb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariadbList) DeepCopyInto(out *MariadbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mariadb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariadbList.
func (in *MariadbList) DeepCopy() *MariadbList {
	if in == nil {
		return nil
	}
	out := new(MariadbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariadbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariadbSpec) DeepCopyInto(out *MariadbSpec) {
	*out = *in
	out.Alert = in.Alert
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariadbSpec.
func (in *MariadbSpec) DeepCopy() *MariadbSpec {
	if in == nil {
		return nil
	}
	out := new(MariadbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAlert) DeepCopyInto(out *MongoDBAlert) {
	*out = *in
	out.RuleSelector = in.RuleSelector
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAlert.
func (in *MongoDBAlert) DeepCopy() *MongoDBAlert {
	if in == nil {
		return nil
	}
	out := new(MongoDBAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAlertRules) DeepCopyInto(out *MongoDBAlertRules) {
	*out = *in
	out.MongodbVirtualMemoryUsage = in.MongodbVirtualMemoryUsage
	out.MongodbReplicationLag = in.MongodbReplicationLag
	out.MongodbNumberCursorsOpen = in.MongodbNumberCursorsOpen
	out.MongodbCursorsTimeouts = in.MongodbCursorsTimeouts
	out.MongodbTooManyConnections = in.MongodbTooManyConnections
	out.MongoDBPhaseCritical = in.MongoDBPhaseCritical
	out.MongoDBDown = in.MongoDBDown
	out.MongodbHighLatency = in.MongodbHighLatency
	out.MongodbHighTicketUtilization = in.MongodbHighTicketUtilization
	out.MongodbRecurrentCursorTimeout = in.MongodbRecurrentCursorTimeout
	out.MongodbRecurrentMemoryPageFaults = in.MongodbRecurrentMemoryPageFaults
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAlertRules.
func (in *MongoDBAlertRules) DeepCopy() *MongoDBAlertRules {
	if in == nil {
		return nil
	}
	out := new(MongoDBAlertRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mongodb) DeepCopyInto(out *Mongodb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mongodb.
func (in *Mongodb) DeepCopy() *Mongodb {
	if in == nil {
		return nil
	}
	out := new(Mongodb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mongodb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbList) DeepCopyInto(out *MongodbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mongodb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbList.
func (in *MongodbList) DeepCopy() *MongodbList {
	if in == nil {
		return nil
	}
	out := new(MongodbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongodbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbSpec) DeepCopyInto(out *MongodbSpec) {
	*out = *in
	out.Alert = in.Alert
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbSpec.
func (in *MongodbSpec) DeepCopy() *MongodbSpec {
	if in == nil {
		return nil
	}
	out := new(MongodbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLAlert) DeepCopyInto(out *MySQLAlert) {
	*out = *in
	out.RuleSelector = in.RuleSelector
	out.Groups = in.Groups
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLAlert.
func (in *MySQLAlert) DeepCopy() *MySQLAlert {
	if in == nil {
		return nil
	}
	out := new(MySQLAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLAlertGroups) DeepCopyInto(out *MySQLAlertGroups) {
	*out = *in
	out.Database = in.Database
	out.Group = in.Group
	out.Kubedb = in.Kubedb
	out.Opsrequest = in.Opsrequest
	out.Stash = in.Stash
	out.Schema = in.Schema
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLAlertGroups.
func (in *MySQLAlertGroups) DeepCopy() *MySQLAlertGroups {
	if in == nil {
		return nil
	}
	out := new(MySQLAlertGroups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLDatabase) DeepCopyInto(out *MySQLDatabase) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLDatabase.
func (in *MySQLDatabase) DeepCopy() *MySQLDatabase {
	if in == nil {
		return nil
	}
	out := new(MySQLDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLDatabaseRules) DeepCopyInto(out *MySQLDatabaseRules) {
	*out = *in
	out.MySQLInstanceDown = in.MySQLInstanceDown
	out.MySQLServiceDown = in.MySQLServiceDown
	out.MySQLTooManyConnections = in.MySQLTooManyConnections
	out.MySQLHighThreadsRunning = in.MySQLHighThreadsRunning
	out.MySQLSlowQueries = in.MySQLSlowQueries
	out.MySQLInnoDBLogWaits = in.MySQLInnoDBLogWaits
	out.MySQLRestarted = in.MySQLRestarted
	out.MySQLHighQPS = in.MySQLHighQPS
	out.MySQLHighIncomingBytes = in.MySQLHighIncomingBytes
	out.MySQLHighOutgoingBytes = in.MySQLHighOutgoingBytes
	out.MySQLTooManyOpenFiles = in.MySQLTooManyOpenFiles
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLDatabaseRules.
func (in *MySQLDatabaseRules) DeepCopy() *MySQLDatabaseRules {
	if in == nil {
		return nil
	}
	out := new(MySQLDatabaseRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLGroup) DeepCopyInto(out *MySQLGroup) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLGroup.
func (in *MySQLGroup) DeepCopy() *MySQLGroup {
	if in == nil {
		return nil
	}
	out := new(MySQLGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLGroupRules) DeepCopyInto(out *MySQLGroupRules) {
	*out = *in
	out.MySQLHighReplicationDelay = in.MySQLHighReplicationDelay
	out.MySQLHighReplicationTransportTime = in.MySQLHighReplicationTransportTime
	out.MySQLHighReplicationApplyTime = in.MySQLHighReplicationApplyTime
	out.MySQLReplicationHighTransactionTime = in.MySQLReplicationHighTransactionTime
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLGroupRules.
func (in *MySQLGroupRules) DeepCopy() *MySQLGroupRules {
	if in == nil {
		return nil
	}
	out := new(MySQLGroupRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLKubedb) DeepCopyInto(out *MySQLKubedb) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLKubedb.
func (in *MySQLKubedb) DeepCopy() *MySQLKubedb {
	if in == nil {
		return nil
	}
	out := new(MySQLKubedb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLKubedbRules) DeepCopyInto(out *MySQLKubedbRules) {
	*out = *in
	out.KubeDBMySQLPhaseNotReady = in.KubeDBMySQLPhaseNotReady
	out.KubeDBMySQLPhaseCritical = in.KubeDBMySQLPhaseCritical
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLKubedbRules.
func (in *MySQLKubedbRules) DeepCopy() *MySQLKubedbRules {
	if in == nil {
		return nil
	}
	out := new(MySQLKubedbRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLOpsrequest) DeepCopyInto(out *MySQLOpsrequest) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLOpsrequest.
func (in *MySQLOpsrequest) DeepCopy() *MySQLOpsrequest {
	if in == nil {
		return nil
	}
	out := new(MySQLOpsrequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLOpsrequestRules) DeepCopyInto(out *MySQLOpsrequestRules) {
	*out = *in
	out.KubeDBMySQLOpsRequestOnProgress = in.KubeDBMySQLOpsRequestOnProgress
	out.KubeDBMySQLOpsRequestStatusProgressingToLong = in.KubeDBMySQLOpsRequestStatusProgressingToLong
	out.KubeDBMySQLOpsRequestFailed = in.KubeDBMySQLOpsRequestFailed
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLOpsrequestRules.
func (in *MySQLOpsrequestRules) DeepCopy() *MySQLOpsrequestRules {
	if in == nil {
		return nil
	}
	out := new(MySQLOpsrequestRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLSchema) DeepCopyInto(out *MySQLSchema) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLSchema.
func (in *MySQLSchema) DeepCopy() *MySQLSchema {
	if in == nil {
		return nil
	}
	out := new(MySQLSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLSchemaRules) DeepCopyInto(out *MySQLSchemaRules) {
	*out = *in
	out.KubeDBMySQLSchemaPendingForTooLong = in.KubeDBMySQLSchemaPendingForTooLong
	out.KubeDBMySQLSchemaInProgressForTooLong = in.KubeDBMySQLSchemaInProgressForTooLong
	out.KubeDBMySQLSchemaTerminatingForTooLong = in.KubeDBMySQLSchemaTerminatingForTooLong
	out.KubeDBMySQLSchemaFailed = in.KubeDBMySQLSchemaFailed
	out.KubeDBMySQLSchemaExpired = in.KubeDBMySQLSchemaExpired
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLSchemaRules.
func (in *MySQLSchemaRules) DeepCopy() *MySQLSchemaRules {
	if in == nil {
		return nil
	}
	out := new(MySQLSchemaRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLStash) DeepCopyInto(out *MySQLStash) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLStash.
func (in *MySQLStash) DeepCopy() *MySQLStash {
	if in == nil {
		return nil
	}
	out := new(MySQLStash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLStashRules) DeepCopyInto(out *MySQLStashRules) {
	*out = *in
	out.MySQLStashBackupSessionFailed = in.MySQLStashBackupSessionFailed
	out.MySQLStashRestoreSessionFailed = in.MySQLStashRestoreSessionFailed
	out.MySQLStashNoBackupSessionForTooLong = in.MySQLStashNoBackupSessionForTooLong
	out.MySQLStashRepositoryCorrupted = in.MySQLStashRepositoryCorrupted
	out.MySQLStashRepositoryStorageRunningLow = in.MySQLStashRepositoryStorageRunningLow
	out.MySQLStashBackupSessionPeriodTooLong = in.MySQLStashBackupSessionPeriodTooLong
	out.MySQLStashRestoreSessionPeriodTooLong = in.MySQLStashRestoreSessionPeriodTooLong
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLStashRules.
func (in *MySQLStashRules) DeepCopy() *MySQLStashRules {
	if in == nil {
		return nil
	}
	out := new(MySQLStashRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mysql) DeepCopyInto(out *Mysql) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mysql.
func (in *Mysql) DeepCopy() *Mysql {
	if in == nil {
		return nil
	}
	out := new(Mysql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mysql) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MysqlList) DeepCopyInto(out *MysqlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mysql, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MysqlList.
func (in *MysqlList) DeepCopy() *MysqlList {
	if in == nil {
		return nil
	}
	out := new(MysqlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MysqlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MysqlSpec) DeepCopyInto(out *MysqlSpec) {
	*out = *in
	out.Alert = in.Alert
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MysqlSpec.
func (in *MysqlSpec) DeepCopy() *MysqlSpec {
	if in == nil {
		return nil
	}
	out := new(MysqlSpec)
	in.DeepCopyInto(out)
	return out
}
