properties:
  form:
    properties:
      alert:
        properties:
          additionalRuleLabels:
            additionalProperties:
              type: string
            type: object
          annotations:
            additionalProperties:
              type: string
            type: object
          enabled:
            enum:
            - none
            - critical
            - warning
            - info
            type: string
          groups:
            properties:
              database:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      KafkaAbnormalControllerState:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaBrokerCount:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaISRExpandRate:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaISRShrinkRate:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaNetworkProcessorIdlePercent:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaOfflineLogDirectoryCount:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaOfflinePartitions:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaReplicaFetcherManagerMaxLag:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaTopicCount:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaUnderMinIsrPartitionCount:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      KafkaUnderReplicatedPartitions:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      diskAlmostFull:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      diskUsageHigh:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      kafkaDown:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      kafkaPhaseCritical:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      kafkaRequestHandlerIdlePercent:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - KafkaAbnormalControllerState
                    - KafkaBrokerCount
                    - KafkaISRExpandRate
                    - KafkaISRShrinkRate
                    - KafkaNetworkProcessorIdlePercent
                    - KafkaOfflineLogDirectoryCount
                    - KafkaOfflinePartitions
                    - KafkaReplicaFetcherManagerMaxLag
                    - KafkaTopicCount
                    - KafkaUnderMinIsrPartitionCount
                    - KafkaUnderReplicatedPartitions
                    - diskAlmostFull
                    - diskUsageHigh
                    - kafkaDown
                    - kafkaPhaseCritical
                    - kafkaRequestHandlerIdlePercent
                    type: object
                required:
                - enabled
                - rules
                type: object
              opsManager:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      opsRequestFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      opsRequestOnProgress:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      opsRequestStatusProgressingToLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - opsRequestFailed
                    - opsRequestOnProgress
                    - opsRequestStatusProgressingToLong
                    type: object
                required:
                - enabled
                - rules
                type: object
              provisioner:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      appPhaseCritical:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      appPhaseNotReady:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - appPhaseCritical
                    - appPhaseNotReady
                    type: object
                required:
                - enabled
                - rules
                type: object
            required:
            - database
            - opsManager
            - provisioner
            type: object
          labels:
            additionalProperties:
              type: string
            type: object
        required:
        - enabled
        - groups
        - labels
        type: object
    required:
    - alert
    type: object
  grafana:
    properties:
      apikey:
        type: string
      enabled:
        type: boolean
      jobName:
        type: string
      url:
        type: string
      version:
        type: string
    required:
    - apikey
    - enabled
    - jobName
    - url
    - version
    type: object
  metadata:
    properties:
      release:
        properties:
          name:
            type: string
          namespace:
            type: string
        required:
        - name
        - namespace
        type: object
      resource:
        description: ResourceID identifies a resource
        properties:
          group:
            type: string
          kind:
            description: Kind is the serialized kind of the resource.  It is normally
              CamelCase and singular.
            type: string
          name:
            description: 'Name is the plural name of the resource to serve.  It must
              match the name of the CustomResourceDefinition-registration too: plural.group
              and it must be all lowercase.'
            type: string
          scope:
            description: ResourceScope is an enum defining the different scopes available
              to a custom resource
            type: string
          version:
            type: string
        required:
        - group
        type: object
    required:
    - release
    - resource
    type: object
required:
- form
- grafana
type: object
