metadata:
  resource:
    group: kubedb.com
    kind: ZooKeeper
    name: zookeepers
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""

form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          # ZooKeeper is down
          zookeeperDown:
            enabled: true
            duration: "1m"
            severity: critical
          # ZooKeeper has way too nodes. Consider scaling up.
          zookeeperTooManyNodes:
            enabled: true
            duration: "1m"
            val: 1000000
            severity: warning
          # ZooKeeper is allocated too big memory
          zookeeperTooBigMemory:
            enabled: true
            duration: "1m"
            val: 1
            severity: warning
          # ZooKeeper is watching many nodes
          zookeeperTooManyWatch:
            enabled: true
            duration: "1m"
            val: 10000
            severity: warning
          # ZooKeeper has created too many connections
          zookeeperTooManyConnections:
            enabled: true
            duration: "1m"
            val: 60
            severity: warning
          # ZooKeeper leader election happened
          zookeeperLeaderElection:
            enabled: true
            duration: "1m"
            severity: warning
          # Openfile count in zookeeper is more than 300
          zookeeperTooManyOpenFiles:
            enabled: true
            duration: "1m"
            val: 300
            severity: warning
          # ZooKeeper is taking more time to sync
          zookeeperTooLongFsyncTime:
            enabled: true
            duration: "1m"
            val: 100
            severity: warning
          # ZooKeeper is taking more time when taking snapshots
          zookeeperTooLongSnapshotTime:
            enabled: true
            duration: "1m"
            val: 100
            severity: warning
          # Average latency is too high
          zookeeperTooHighAvgLatency:
            enabled: true
            duration: "1m"
            val: 100
            severity: warning
          # ZooKeeper jvm memory is filling up
          zookeeperJvmMemoryFilingUp:
            enabled: true
            duration: "1m"
            val: 0.8
            severity: warning
          # Sepcifies the alert configuration for persistent volume usages.
          diskUsageHigh:
            enabled: true
            val: 80
            duration: "1m"
            severity: warning
          diskAlmostFull:
            enabled: true
            val: 95
            duration: "1m"
            severity: critical


      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

      opsManager:
        enabled: warning
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical

grafana:
  enabled: false
  version: 7.5.5
  jobName: kubedb-databases
  url: ""
  apikey: ""
