project:
  name: Cassandra alerts by AppsCode
  shortName: Cassandra alerts
  url: https://github.com/appscode/alerts
  description: Cassandra alerts for KubeDB
  app: Cassandra alerts
repository:
  url: oci://ghcr.io/appscode-charts
  name: appscode
chart:
  name: cassandra
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
  - Kubernetes 1.19+
release:
  name: cassandra
  namespace: demo