{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hanadb-alerts.fullname" . }}-configmap
  labels:
    {{- include "hanadb-alerts.labels" . | nindent 4 }}

data:
  grafana-json.json: |-
    {
      "dashboard": {
        "__inputs": [],
        "__requires": [
          {
            "type": "grafana",
            "id": "grafana",
            "name": "Grafana",
            "version": "{{ .Values.grafana.version }}"
          },
          {
            "type": "panel",
            "id": "graph",
            "name": "Graph",
            "version": ""
          }
        ],
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": "-- Grafana --",
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "id": null,
        "links": [],
        "panels": [
          {
            "collapsed": false,
            "datasource": null,
            "gridPos": {
              "h": 1,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 20,
            "panels": [],
            "title": "HanaDB Phase",
            "type": "row"
          },
          {
            "alert": {
              "alertRuleTags": {},
              "conditions": [
                {
                  "evaluator": {
                    "params": [
                      0
                    ],
                    "type": "gt"
                  },
                  "operator": {
                    "type": "and"
                  },
                  "query": {
                    "params": [
                      "A",
                      "5m",
                      "now"
                    ]
                  },
                  "reducer": {
                    "params": [],
                    "type": "last"
                  },
                  "type": "query"
                }
              ],
              "executionErrorState": "alerting",
              "for": "{{ .Values.form.alert.groups.provisioner.rules.appPhaseNotReady.duration }}",
              "frequency": "1m",
              "handler": 1,
              "name": "KubeDB HanaDB Phase Not Ready",
              "noDataState": "no_data",
              "notifications": []
            },
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": null,
            "fieldConfig": {
              "defaults": {},
              "overrides": []
            },
            "fill": 1,
            "fillGradient": 0,
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 1
            },
            "hiddenSeries": false,
            "id": 22,
            "legend": {
              "avg": false,
              "current": false,
              "max": false,
              "min": false,
              "show": true,
              "total": false,
              "values": false
            },
            "lines": true,
            "linewidth": 1,
            "nullPointMode": "null",
            "options": {
              "alertThreshold": true
            },
            "percentage": false,
            "pluginVersion": "7.5.5",
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [
              {
                "exemplar": true,
                "expr": "kubedb_com_hanadb_status_phase{app=\"{{ .Release.Name }}\",namespace=\"{{ .Release.Namespace }}\",phase=\"NotReady\"}",
                "interval": "",
                "legendFormat": "",
                "refId": "A"
              }
            ],
            "thresholds": [
              {
                "colorMode": "critical",
                "fill": true,
                "line": true,
                "op": "gt",
                "value": 0,
                "visible": true
              }
            ],
            "title": "KubeDB HanaDB Phase Not Ready",
            "tooltip": {
              "shared": true,
              "sort": 0,
              "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              },
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              }
            ],
            "yaxis": {
              "align": false,
              "alignLevel": null
            }
          },
          {
            "alert": {
              "alertRuleTags": {},
              "conditions": [
                {
                  "evaluator": {
                    "params": [
                      0
                    ],
                    "type": "gt"
                  },
                  "operator": {
                    "type": "and"
                  },
                  "query": {
                    "params": [
                      "A",
                      "5m",
                      "now"
                    ]
                  },
                  "reducer": {
                    "params": [],
                    "type": "last"
                  },
                  "type": "query"
                }
              ],
              "executionErrorState": "alerting",
              "for": "{{ .Values.form.alert.groups.provisioner.rules.appPhaseCritical.duration }}",
              "frequency": "1m",
              "handler": 1,
              "name": "KubeDB HanaDB Phase Critical",
              "noDataState": "no_data",
              "notifications": []
            },
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": null,
            "fieldConfig": {
              "defaults": {},
              "overrides": []
            },
            "fill": 1,
            "fillGradient": 0,
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 1
            },
            "hiddenSeries": false,
            "id": 24,
            "legend": {
              "avg": false,
              "current": false,
              "max": false,
              "min": false,
              "show": true,
              "total": false,
              "values": false
            },
            "lines": true,
            "linewidth": 1,
            "nullPointMode": "null",
            "options": {
              "alertThreshold": true
            },
            "percentage": false,
            "pluginVersion": "7.5.5",
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [
              {
                "exemplar": true,
                "expr": "kubedb_com_hanadb_status_phase{app=\"{{ .Release.Name }}\",namespace=\"{{ .Release.Namespace }}\",phase=\"Critical\"}",
                "interval": "",
                "legendFormat": "",
                "refId": "A"
              }
            ],
            "thresholds": [
              {
                "colorMode": "critical",
                "fill": true,
                "line": true,
                "op": "gt",
                "value": 0,
                "visible": true
              }
            ],
            "title": "KubeDB HanaDB Phase Critical",
            "tooltip": {
              "shared": true,
              "sort": 0,
              "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              },
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              }
            ],
            "yaxis": {
              "align": false,
              "alignLevel": null
            }
          }
        ],
        "schemaVersion": 27,
        "style": "dark",
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-30m",
          "to": "now"
        },
        "title": "HanaDB Alerts",
        "version": 1
      },
      "overwrite": true
    }
{{- end }}
