apiVersion: v2
name: singlestore-alerts
description: A Helm chart for Singlestore Alert by AppsCode
type: application
version: v2025.3.24
appVersion: v0.4.0
home: https://github.com/appscode/alerts
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/appscode/alerts
maintainers:
- name: appscode
  email: support@appscode.com
