metadata:
  resource:
    group: apps
    kind: StatefulSet
    name: statefulsets
    scope: Namespaced
    version: v1
  release:
    name: ""
    namespace: ""

form:
  alert:
    enabled: warning
    labels: # +doc-gen:break
      release: kube-prometheus-stack
    annotations: {}
    additionalRuleLabels: {}

    groups:
      process:
        enabled: warning
        rules:
          b3Down:
            enabled: true
            duration: "2m"
            severity: critical
          b3ReplicasNotReady:
            enabled: true
            duration: "2m"
            severity: critical
          b3HighGoroutineCount:
            enabled: true
            duration: "10m"
            severity: warning
            val: 10000
          b3HighGcPauseDuration:
            enabled: true
            duration: "5m"
            severity: warning
            val: 0.2
          b3HighFileDescriptorUsage:
            enabled: true
            duration: "5m"
            severity: warning
            val: 80

      http:
        enabled: warning
        rules:
          b3HighHttpErrorRate:
            enabled: true
            duration: "5m"
            severity: critical
            val: 5
          b3HighHttpLatency:
            enabled: true
            duration: "5m"
            severity: warning
            val: 1
          b3HighActiveRequests:
            enabled: true
            duration: "5m"
            severity: warning
            val: 1000

      database:
        enabled: warning
        rules:
          b3HighDatabaseErrorRate:
            enabled: true
            duration: "5m"
            severity: critical
            val: 5
          b3HighDatabaseLatency:
            enabled: true
            duration: "5m"
            severity: warning
            val: 0.5
          b3DatabaseConnectionErrors:
            enabled: true
            duration: "5m"
            severity: critical
            val: 5
          b3HighDatabaseConnectionPoolUsage:
            enabled: true
            duration: "5m"
            severity: warning
            val: 80

      auth:
        enabled: warning
        rules:
          b3HighAuthFailureRate:
            enabled: true
            duration: "5m"
            severity: warning
            val: 10
          b3HighAuthzDenialRate:
            enabled: true
            duration: "5m"
            severity: warning
            val: 10

      storage:
        enabled: warning
        rules:
          b3HighBlobStorageErrorRate:
            enabled: true
            duration: "5m"
            severity: warning
            val: 5

      proxy:
        enabled: warning
        rules:
          b3HighProxyErrorRate:
            enabled: true
            duration: "5m"
            severity: warning
            val: 5
          b3HighProxyLatency:
            enabled: true
            duration: "5m"
            severity: warning
            val: 5

grafana:
  enabled: false
  version: 8.2.3
  jobName: ace-platform-api
  url: ""
  apikey: ""
