metadata:
  resource:
    group: kubedb.com
    kind: MongoDB
    name: mongodbs
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""

form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          # Sepcifies the alert configuration for virtual memory usage.
          mongodbVirtualMemoryUsage:
            enabled: true
            val: 2097152 # 2GB
            duration: "1m"
            severity: warning
          # Sepcifies the alert configuration for replication lag.
          mongodbReplicationLag:
            enabled: true
            val: 10
            duration: "0m"
            severity: critical
          # Sepcifies the alert configuration for number of opened cursors are more than a specified amount.
          mongodbNumberCursorsOpen:
            enabled: true
            val: 10000
            duration: "2m"
            severity: warning
          # Sepcifies the alert configuration for timed out cursors.
          mongodbCursorsTimeouts:
            enabled: true
            val: 100
            duration: "2m"
            severity: warning
          # Sepcifies the alert configuration for too many connections are opened.
          mongodbTooManyConnections:
            enabled: true
            val: 80 # percentage
            duration: "2m"
            severity: warning
          # Sepcifies the alert configuration for database is in Critical phase, that means one or more of the nodes are down but the database read/write are not hampered.
          mongoDBPhaseCritical:
            enabled: true
            duration: "10m"
            severity: warning
          # Sepcifies the alert configuration for database is in NotReady phase, that means the database is not accepting connections, read/write are hampered.
          mongoDBDown:
            enabled: true
            duration: "30s"
            severity: critical
          # Sepcifies the alert configuration for high latency.
          mongodbHighLatency:
            enabled: true
            val: 250000
            duration: "10m"
            severity: warning
          # Sepcifies the alert configuration for high ticket utilizations.
          mongodbHighTicketUtilization:
            enabled: true
            val: 75 # percentage
            duration: "10m"
            severity: warning
          # Sepcifies the alert configuration for recurrent cursor timeout.
          mongodbRecurrentCursorTimeout:
            enabled: true
            val: 0
            duration: "30m"
            severity: warning
          # Sepcifies the alert configuration for recurrent memory page faults.
          mongodbRecurrentMemoryPageFaults:
            enabled: true
            val: 0
            duration: "30m"
            severity: warning
          # Sepcifies the alert configuration for persistent volume usages.
          diskUsageHigh:
            enabled: true
            val: 80
            duration: "1m"
            severity: warning
          diskAlmostFull:
            enabled: true
            val: 95
            duration: "1m"
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning
      opsManager:
        enabled: warning
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical
      stash:
        enabled: warning
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: warning
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: warning
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
      schemaManager:
        enabled: warning
        rules:
          schemaPendingForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaInProgressForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaTerminatingForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaFailed:
            enabled: true
            duration: "0m"
            severity: warning
          schemaExpired:
            enabled: true
            duration: "0m"
            severity: warning


grafana:
  enabled: false
  version: 7.5.5
  jobName: kubedb-databases
  url: ""
  apikey: ""
