metadata:
  resource:
    group: apps
    kind: Deployment
    name: deployments
    scope: Namespaced
    version: v1
  release:
    name: ""
    namespace: ""

form:
  alert:
    enabled: warning

    labels:
      release: kube-prometheus-stack

    annotations: {}

    additionalRuleLabels: {}

    groups:
      core:
        enabled: warning
        rules:
          down:
            enabled: true
            duration: "2m"
            severity: critical
          highRequestLatency:
            enabled: true
            duration: "5m"
            val: 1.0
            severity: critical
          highErrorRate:
            enabled: true
            duration: "5m"
            val: 5
            severity: critical
          lowCheckCacheHitRatio:
            enabled: true
            duration: "5m"
            val: 70
            severity: warning
          highSQLConnections:
            enabled: true
            duration: "5m"
            val: 80
            severity: critical

grafana:
  enabled: false
  version: 8.2.3
  jobName: openfga
  url: ""
  apikey: ""
