metadata:
  resource:
    group: kubedb.com
    kind: Druid
    name: druids
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""
form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: prometheus

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          # Specifies the alert configuration for one of the service of druid is down
          druidDown:
            enabled: true
            duration: "1m"
            severity: critical
          # Specifies the alert configuration for Druid lost connection to ZooKeeper
          zkDisconnected:
            enabled: true
            duration: "1m"
            severity: critical
          # Specifies the alert configuration for Druid high query time
          highQueryTime:
            enabled: true
            duration: "1m"
            severity: warning
          # Specifies the alert configuration for Druid high query wait time
          highQueryWaitTime:
            enabled: true
            duration: "1m"
            severity: warning
          # Specifies the alert configuration for high number of segments in pending
          highSegmentScanPending:
            enabled: true
            duration: "1m"
            severity: warning
            val: 2
          # Specifies the alert configuration for high percentage of segment usage
          highSegmentUsage:
            enabled: true
            duration: "1m"
            severity: critical
            val: 95
          # Specifies the alert configuration for high percentage of jvm pool usage
          highJVMPoolUsage:
            enabled: true
            duration: "30s"
            severity: warning
            val: 95
          # Specifies the alert configuration for high percentage of jvm memory usage
          highJVMMemoryUsage:
            enabled: true
            duration: "30s"
            severity: critical
            val: 95
      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

grafana:
  enabled: false
  version: 8.2.3
  jobName: kubedb-databases
  url: ""
  apikey: ""
