metadata:
  resource:
    group: kubedb.com
    kind: MSSQLServer
    name: mssqlserveres
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: "mssql-ag"
    # Release namespace
    namespace: "demo"

form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          mssqlserverInstanceDown:
            enabled: true
            duration: "0m"
            severity: critical
          # Specifies the alert configuration for service is down.
          mssqlserverServiceDown:
            enabled: true
            duration: "0m"
            severity: critical
          mssqlserverRestarted:
            enabled: true
            duration: "0m"
            val: 60
            severity: critical
          # Sepcifies the alert configuration for persistent volume usages.
          diskUsageHigh:
            enabled: true
            val: 80
            duration: "1m"
            severity: warning
          diskAlmostFull:
            enabled: true
            val: 95
            duration: "1m"
            severity: critical

      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

      opsManager:
        enabled: warning
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical

      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: warning
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning

grafana:
  enabled: false
  version: 7.5.5
  jobName: kubedb-databases
  url: ""
  apikey: ""
