metadata:
  resource:
    group: kubedb.com
    kind: Hazelcast
    name: hazelcasts
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: "hazelcast-sample"
    # Release namespace
    namespace: "default"
form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          # Specifies the alert configuration for database is in Critical phase, that means one or more of the nodes are down but the database read/write are not hampered.
          hazelcastPhaseCritical:
            enabled: true
            duration: "3m"
            severity: warning
          # Specifies the alert configuration for database is in NotReady phase, that means the database is not accepting connections, read/write are hampered.
          hazelcastDown:
            enabled: true
            duration: "30s"
            severity: critical
          # Specifies the alert configuration for partition count.
          hazelcastPartitionCountExceed:
            enabled: true
            duration: "30s"
            severity: warning
            val: 92
          # Specifies the alert configuration for high heap percentahe.
          hazelcastHighHeapPercentage:
            enabled: true
            duration: "30s"
            severity: warning
            val: 80
          # Specifies alert configuration for high memory usage
          hazelcastHighMemoryUsage:
            enabled: true
            duration: "30s"
            severity: warning
            val: 80
          # Specifies alert configuration for high physical emory usage
          hazelcastHighPhysicalMemoryUsage:
            enabled: true
            duration: "30s"
            severity: warning
            val: 50
          # Specifies alert configuration for high latency
          hazelcastHighLatency:
            enabled: true
            duration: "30s"
            severity: warning
            val: 2.5
          # Specifies alert configuration for high cpu load
          hazelcastSystemCPULoadExceed:
            enabled: true
            duration: "30s"
            severity: warning
            val: 5
          # Sepcifies the alert configuration for persistent volume usages.
          diskUsageHigh:
            enabled: true
            val: 80
            duration: "1m"
            severity: warning
          diskAlmostFull:
            enabled: true
            val: 95
            duration: "1m"
            severity: critical

      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

      opsManager:
        enabled: warning
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical

grafana:
  enabled: true
  version: 7.5.5
  jobName: kubedb-databases
  url: ""
  apikey: ""
